alter table `accounts` add index `accounts_name_index`(`name`);
alter table `doctor_opd_charges` add index `doctor_opd_charges_created_at_index`(`created_at`);
alter table `bed_assigns` add index `bed_assigns_created_at_assign_date_index`(`created_at`, `assign_date`);
 alter table `medicines` add index `medicines_name_index`(`name`);
 alter table `employee_payrolls` add index `employee_payrolls_id_sr_no_index`(`id`, `sr_no`);
 alter table `notice_boards` add index `notice_boards_created_at_id_index`(`created_at`, `id`);
 alter table `blood_donors` add index `blood_donors_created_at_last_donate_date_index`(`created_at`, `last_donate_date`);
 alter table `packages` add index `packages_created_at_name_index`(`created_at`, `name`);
 alter table `bed_types` add index `bed_types_title_index`(`title`);
 alter table `services` add index `services_name_index`(`name`);
 alter table `invoices` add index `invoices_invoice_date_index`(`invoice_date`);
 alter table `payments` add index `payments_payment_date_index`(`payment_date`);
 alter table `advanced_payments` add index `advanced_payments_amount_index`(`amount`);
 alter table `bills` add index `bills_bill_date_index`(`bill_date`);
 alter table `beds` add index `beds_is_available_index`(`is_available`);
 alter table `blood_banks` add index `blood_banks_remained_bags_index`(`remained_bags`);
 alter table `users` add index `users_first_name_index`(`first_name`);
 alter table `patient_cases` add index `patient_cases_date_index`(`date`);
 alter table `patient_admissions` add index `patient_admissions_admission_date_index`(`admission_date`);
 alter table `document_types` add index `document_types_name_index`(`name`);
 alter table `insurances` add index `insurances_name_index`(`name`);
 alter table `ambulances` add index `ambulances_vehicle_number_index`(`vehicle_number`);
 alter table `ambulance_calls` add index `ambulance_calls_date_index`(`date`);
 alter table `doctor_departments` add index `doctor_departments_title_index`(`title`);
 alter table `appointments` add index `appointments_opd_date_index`(`opd_date`);
 alter table `birth_reports` add index `birth_reports_date_index`(`date`);
 alter table `death_reports` add index `death_reports_date_index`(`date`);
 alter table `investigation_reports` add index `investigation_reports_date_index`(`date`);
 alter table `operation_reports` add index `operation_reports_date_index`(`date`);
 alter table `categories` add index `categories_name_index`(`name`);
 alter table `brands` add index `brands_name_index`(`name`);
 alter table `pathology_tests` add index `pathology_tests_test_name_index`(`test_name`);
 alter table `pathology_categories` add index `pathology_categories_name_index`(`name`);
 alter table `radiology_tests` add index `radiology_tests_test_name_index`(`test_name`);
 alter table `radiology_categories` add index `radiology_categories_name_index`(`name`);
 alter table `expenses` add index `expenses_date_index`(`date`);
 alter table `incomes` add index `incomes_date_index`(`date`);
 alter table `charges` add index `charges_code_index`(`code`);
 alter table `charge_categories` add index `charge_categories_name_index`(`name`);
 alter table `enquiries` add index `enquiries_created_at_index`(`created_at`);  

